### ISSUE TITLE
OpenSSH 7.5 deprecated option UsePrivilegeSeparation

### ISSUE THREAD

**Issue by jpalko** [willshersystems/ansible-sshd#145]
Noticed this in a CentOS 8 system journal log:
sshd[2307]: /etc/ssh/sshd_config line 19: Deprecated option UsePrivilegeSeparation
and checked on OpenSSH release information here:
https://www.openssh.com/txt/release-7.5

Potentially-incompatible changes
================================

This release includes a number of changes that may affect existing
configurations:

 * This release deprecates the sshd_config UsePrivilegeSeparation
   option, thereby making privilege separation mandatory. Privilege
   separation has been on by default for almost 15 years and
   sandboxing has been on by default for almost the last five.

**Comment by Jakuje** [comment]
This option is not in [defaults of RHEL 8/CentOS 8](https://github.com/willshersystems/ansible-sshd/blob/master/vars/RedHat_8.yml) so you see this warning probably because you have it in your playbook.

There are dozens of other deprecated/removed configuration options in current OpenSSH over the years, but as the role role can be used to configure older operating systems with this option, I do not think it is time to remove this option from the role completely. I also do not think the role should automatically trim unsupported options from your provided configuration options as it can cause different than intended configuration silently.

What is your proposal to fix this issue?

**Comment by jpalko** [comment]
Sorry, looks like the system was deployed using an old unupdated playbook. No change needed. :+1:

**Comment by mattwillsher** [comment]
Thanks both. Closing.
