### ISSUE TITLE
sshd_packages unlikely to be overridable

### ISSUE THREAD

**Issue by shk3bq4d** [willshersystems/ansible-sshd#170]
README.md says sshd_packages is free to be overridden. but I don't think the current implementation allows that as the include_vars will unconditionally load one file that would override user selection

maybe a fix would include the use of sshd_skip_defaults ?

**Comment by Jakuje** [comment]
The `sshd_packages` and others are listed under "Secondary role variables". You are able to override it with role arguments if used as within `include_role`, but because of the variable precedence limitation in ansible, its not easy to override them when used with "old" "roles:".

But this variable should be quite static and considered private in the first place, as it is based on the OS. If you need to install some add additional package, it might make sense to provide `sshd_additional_packages` which will be added to the installed list and which should be trivial to add.

**Comment by nkakouros** [comment]
This is fixed in #199.

**Comment by Jakuje** [comment]
This was fixed with #199 and it will be in the next release.
