### ISSUE TITLE
Missing privilege separation directory (/run/sshd)

### ISSUE THREAD

**Issue by theodore86** [willshersystems/ansible-sshd#174]
Hi,

I was tryingto execute your ansible ssh role inside an docker container (ubuntu-20.04) but the task ``willshersystems.sshd : Create the complete configuration file`` is falling due to:

```console
TASK [willshersystems.sshd : Make sure sshd runtime directory is present] ******************************************************************************************************************************
task path: /opt/roles/external/willshersystems.sshd/tasks/install.yml:93
Sunday 21 November 2021  09:42:38 +0000 (0:00:00.609)       0:00:43.001 *******
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [willshersystems.sshd : Create the complete configuration file] 

STDERR:

Missing privilege separation directory: /run/sshd

MSG:

failed to validate
```

It seems that the task ``willshersystems.sshd : Make sure sshd runtime directory is present`` is being skipped due to the the fact that the conditional expression ``__sshd_runtime_directory | d(false) | bool`` is always evaluates to **False** (variable if defined is of a string type).

Maybe we could remove the ``when:`` keyword and let the file module checks if the directory exists or not (and then created)?

Thanks,
Theodore G.

**Comment by Jakuje** [comment]
Thank you for the report. Yeah, the `|bool` is wrong. But we still need this if the sshd daemon is not running. Unfortunately, this is not the case for the Github Actions, where sshd is running and directory in place in all the tests.
On the other hand, this check needs to be skipped on non-Debian systems, which have this directory provided by the operating system (instead of underlying systemd service file).

**Comment by Jakuje** [comment]
@theodore86 can you check the proposed solution in #175 solves the issue for you?

**Comment by theodore86** [comment]
@Jakuje thanks a lot! The proposed solution looks nice.
