### ISSUE TITLE
inconsistent version formats

### ISSUE THREAD

**Issue by nickbroon** [willshersystems/ansible-sshd#98]
I think the mix of version format means that this role cannot easily be install. The only work around is to specify a specific version.

```
- downloading role 'sshd', owned by willshersystems
 [WARNING]: - willshersystems.sshd was NOT installed successfully: Unable to
compare role versions (v0.7.2, 0.2.0, 0.4.1, 0.3.0, 0.4.5, 0.4.3, 0.2.5,
v0.7.1, v0.4.8, v0.4.10, v0.4.9, 0.1.0, 0.5.1, v0.4.7, v0.4.6, v0.6.2, v0.5,
v0.7.0, v0.6.0, 0.4.4, 0.2.3, 0.4.2, 0.4.0, 0.2.1, v0.6.1, 0.2.2, 0.3.1, 0.2.4,
0.3.2) to determine the most recent version due to incompatible version
formats. Please contact the role author to resolve versioning conflicts, or
specify an explicit role version to install.
```

Would it be possible to settle on one format, and delete the versions that use the other?

**Comment by nickbroon** [comment]
This has effected other roles as well. Examples include:
https://github.com/yatesr/ansible-timezone/issues/7
https://github.com/mimacom/ansible-role-bamboo-agent/issues/5

**Comment by cognifloyd** [comment]
This happens when telling `ansible-galaxy` to install this role, and the role is already installed. Earlier versions of `ansible-galaxy` only checked to see if the versions didn't match, and then download the latest. But, newer versions are actually trying to compare the downloaded version with the latest version so that the download only happens if the latest version is newer (and not equal) to the current version. Thus, the error message about an inability to compare the versions with and with the prefixed 'v'.

**Comment by cognifloyd** [comment]
https://twitter.com/cognifloyd/status/1064645755208642560
> To fix galaxy access to willshersystems.sshd could you delete, or prepend `v` on, these tags? 0.2.0, 0.4.1, 0.3.0, 0.4.5, 0.4.3, 0.2.5, 0.1.0, 0.5.1, 0.4.4, 0.2.3, 0.4.2, 0.4.0, 0.2.1, 0.2.2, 0.3.1, 0.2.4, 0.3.2

**Comment by cognifloyd** [comment]
```
for tag in 0.2.0 0.4.1 0.3.0 0.4.5 0.4.3 0.2.5 0.1.0 0.5.1 0.4.4 0.2.3 0.4.2 0.4.0 0.2.1 0.2.2 0.3.1 0.2.4 0.3.2; do
git tag v${tag} ${tag}
git tag -d ${tag}
git push origin :refs/tags/${tag}
done
git push --tags
```

**Comment by mattwillsher** [comment]
Thank @cognifloyd 
I've now done this and all tags are updated in Galaxy.

**Comment by cognifloyd** [comment]
Thanks!
